/**
 * This file was generated by Apache Newt version: 1.4.0-dev
 */

#ifndef H_MYNEWT_SYSCFG_
#define H_MYNEWT_SYSCFG_

/**
 * This macro exists to ensure code includes this header when needed.  If code
 * checks the existence of a setting directly via ifdef without including this
 * header, the setting macro will silently evaluate to 0.  In contrast, an
 * attempt to use these macros without including this header will result in a
 * compiler error.
 */
#define MYNEWT_VAL(x)                            x

/*** compiler/arm-none-eabi-m4 */
#ifndef HARDFLOAT
#define HARDFLOAT (0)
#endif

/*** hw/bsp/nrf52840pdk */
#ifndef BSP_NRF52840
#define BSP_NRF52840 (1)
#endif

#ifndef I2C_0_FREQ_KHZ
#define I2C_0_FREQ_KHZ (100)
#endif

#ifndef I2C_0_PIN_SCL
#define I2C_0_PIN_SCL (27)
#endif

#ifndef I2C_0_PIN_SDA
#define I2C_0_PIN_SDA (26)
#endif

#ifndef PWM_3
#define PWM_3 (0)
#endif

#ifndef SPI_0_MASTER_PIN_MISO
#define SPI_0_MASTER_PIN_MISO (47)
#endif

#ifndef SPI_0_MASTER_PIN_MOSI
#define SPI_0_MASTER_PIN_MOSI (46)
#endif

#ifndef SPI_0_MASTER_PIN_SCK
#define SPI_0_MASTER_PIN_SCK (45)
#endif

#ifndef SPI_0_SLAVE_PIN_MISO
#define SPI_0_SLAVE_PIN_MISO (47)
#endif

#ifndef SPI_0_SLAVE_PIN_MOSI
#define SPI_0_SLAVE_PIN_MOSI (46)
#endif

#ifndef SPI_0_SLAVE_PIN_SCK
#define SPI_0_SLAVE_PIN_SCK (45)
#endif

#ifndef SPI_0_SLAVE_PIN_SS
#define SPI_0_SLAVE_PIN_SS (44)
#endif

#ifndef TIMER_0
#define TIMER_0 (1)
#endif

#ifndef TIMER_1
#define TIMER_1 (0)
#endif

#ifndef TIMER_2
#define TIMER_2 (0)
#endif

#ifndef TIMER_3
#define TIMER_3 (0)
#endif

#ifndef TIMER_4
#define TIMER_4 (0)
#endif

#ifndef TIMER_5
#define TIMER_5 (0)
#endif

#ifndef UART_0
#define UART_0 (1)
#endif

#ifndef UART_0_PIN_CTS
#define UART_0_PIN_CTS (7)
#endif

#ifndef UART_0_PIN_RTS
#define UART_0_PIN_RTS (5)
#endif

#ifndef UART_0_PIN_RX
#define UART_0_PIN_RX (8)
#endif

#ifndef UART_0_PIN_TX
#define UART_0_PIN_TX (6)
#endif

#ifndef UART_1
#define UART_1 (0)
#endif

#ifndef UART_1_PIN_CTS
#define UART_1_PIN_CTS (-1)
#endif

#ifndef UART_1_PIN_RTS
#define UART_1_PIN_RTS (-1)
#endif

#ifndef UART_1_PIN_RX
#define UART_1_PIN_RX (-1)
#endif

#ifndef UART_1_PIN_TX
#define UART_1_PIN_TX (-1)
#endif

/*** hw/mcu/nordic/nrf52xxx */
#ifndef ADC_0
#define ADC_0 (0)
#endif

#ifndef ADC_0_REFMV_0
#define ADC_0_REFMV_0 (0)
#endif

#ifndef I2C_0
#define I2C_0 (0)
#endif

#ifndef I2C_1
#define I2C_1 (0)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef MCU_DCDC_ENABLED
#define MCU_DCDC_ENABLED (1)
#endif

#ifndef MCU_FLASH_MIN_WRITE_SIZE
#define MCU_FLASH_MIN_WRITE_SIZE (1)
#endif

#ifndef PWM_0
#define PWM_0 (0)
#endif

#ifndef PWM_1
#define PWM_1 (0)
#endif

#ifndef PWM_2
#define PWM_2 (0)
#endif

#ifndef QSPI_ADDRMODE
#define QSPI_ADDRMODE (0)
#endif

#ifndef QSPI_DPMCONFIG
#define QSPI_DPMCONFIG (0)
#endif

#ifndef QSPI_ENABLE
#define QSPI_ENABLE (0)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_FLASH_PAGE_SIZE
#define QSPI_FLASH_PAGE_SIZE (256)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_FLASH_SECTOR_COUNT
#define QSPI_FLASH_SECTOR_COUNT (4096)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_FLASH_SECTOR_SIZE
#define QSPI_FLASH_SECTOR_SIZE (4096)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_PIN_CS
#define QSPI_PIN_CS (17)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_PIN_DIO0
#define QSPI_PIN_DIO0 (20)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_PIN_DIO1
#define QSPI_PIN_DIO1 (21)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_PIN_DIO2
#define QSPI_PIN_DIO2 (22)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_PIN_DIO3
#define QSPI_PIN_DIO3 (23)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef QSPI_PIN_SCK
#define QSPI_PIN_SCK (19)
#endif

#ifndef QSPI_READOC
#define QSPI_READOC (0)
#endif

#ifndef QSPI_SCK_DELAY
#define QSPI_SCK_DELAY (0)
#endif

#ifndef QSPI_SCK_FREQ
#define QSPI_SCK_FREQ (0)
#endif

#ifndef QSPI_SPI_MODE
#define QSPI_SPI_MODE (0)
#endif

#ifndef QSPI_WRITEOC
#define QSPI_WRITEOC (0)
#endif

#ifndef SOFT_PWM
#define SOFT_PWM (0)
#endif

#ifndef SPI_0_MASTER
#define SPI_0_MASTER (0)
#endif

#ifndef SPI_0_SLAVE
#define SPI_0_SLAVE (0)
#endif

#ifndef SPI_1_MASTER
#define SPI_1_MASTER (0)
#endif

#ifndef SPI_1_SLAVE
#define SPI_1_SLAVE (0)
#endif

#ifndef SPI_2_MASTER
#define SPI_2_MASTER (0)
#endif

#ifndef SPI_2_SLAVE
#define SPI_2_SLAVE (0)
#endif

/* Overridden by hw/bsp/nrf52840pdk (defined by hw/mcu/nordic/nrf52xxx) */
#ifndef XTAL_32768
#define XTAL_32768 (1)
#endif

#ifndef XTAL_32768_SYNTH
#define XTAL_32768_SYNTH (0)
#endif

#ifndef XTAL_RC
#define XTAL_RC (0)
#endif

/*** kernel/os */
#ifndef FLOAT_USER
#define FLOAT_USER (0)
#endif

#ifndef MSYS_1_BLOCK_COUNT
#define MSYS_1_BLOCK_COUNT (12)
#endif

#ifndef MSYS_1_BLOCK_SIZE
#define MSYS_1_BLOCK_SIZE (292)
#endif

#ifndef MSYS_2_BLOCK_COUNT
#define MSYS_2_BLOCK_COUNT (0)
#endif

#ifndef MSYS_2_BLOCK_SIZE
#define MSYS_2_BLOCK_SIZE (0)
#endif

#ifndef OS_CLI
#define OS_CLI (0)
#endif

#ifndef OS_COREDUMP
#define OS_COREDUMP (0)
#endif

#ifndef OS_CPUTIME_FREQ
#define OS_CPUTIME_FREQ (1000000)
#endif

#ifndef OS_CPUTIME_TIMER_NUM
#define OS_CPUTIME_TIMER_NUM (0)
#endif

#ifndef OS_CTX_SW_STACK_CHECK
#define OS_CTX_SW_STACK_CHECK (0)
#endif

#ifndef OS_CTX_SW_STACK_GUARD
#define OS_CTX_SW_STACK_GUARD (4)
#endif

#ifndef OS_MAIN_STACK_SIZE
#define OS_MAIN_STACK_SIZE (1024)
#endif

#ifndef OS_MAIN_TASK_PRIO
#define OS_MAIN_TASK_PRIO (127)
#endif

#ifndef OS_MEMPOOL_CHECK
#define OS_MEMPOOL_CHECK (0)
#endif

#ifndef OS_MEMPOOL_POISON
#define OS_MEMPOOL_POISON (0)
#endif

#ifndef OS_SCHEDULING
#define OS_SCHEDULING (1)
#endif

#ifndef OS_SYSVIEW
#define OS_SYSVIEW (0)
#endif

#ifndef SANITY_INTERVAL
#define SANITY_INTERVAL (15000)
#endif

#ifndef WATCHDOG_INTERVAL
#define WATCHDOG_INTERVAL (30000)
#endif

/*** libc/baselibc */
#ifndef BASELIBC_ASSERT_FILE_LINE
#define BASELIBC_ASSERT_FILE_LINE (0)
#endif

#ifndef BASELIBC_PRESENT
#define BASELIBC_PRESENT (1)
#endif

/*** nimble */
#ifndef BLE_EXT_ADV
#define BLE_EXT_ADV (0)
#endif

#ifndef BLE_EXT_ADV_MAX_SIZE
#define BLE_EXT_ADV_MAX_SIZE (31)
#endif

#ifndef BLE_MAX_CONNECTIONS
#define BLE_MAX_CONNECTIONS (1)
#endif

#ifndef BLE_MAX_PERIODIC_SYNCS
#define BLE_MAX_PERIODIC_SYNCS (0)
#endif

#ifndef BLE_MULTI_ADV_INSTANCES
#define BLE_MULTI_ADV_INSTANCES (0)
#endif

#ifndef BLE_ROLE_BROADCASTER
#define BLE_ROLE_BROADCASTER (1)
#endif

#ifndef BLE_ROLE_CENTRAL
#define BLE_ROLE_CENTRAL (1)
#endif

#ifndef BLE_ROLE_OBSERVER
#define BLE_ROLE_OBSERVER (1)
#endif

#ifndef BLE_ROLE_PERIPHERAL
#define BLE_ROLE_PERIPHERAL (1)
#endif

#ifndef BLE_WHITELIST
#define BLE_WHITELIST (1)
#endif

/*** nimble/host */
#ifndef BLE_ATT_PREFERRED_MTU
#define BLE_ATT_PREFERRED_MTU (256)
#endif


#ifndef BLE_PERIODIC_ADV
#define BLE_PERIODIC_ADV (0)
#endif

#ifndef BLE_ATT_SVR_FIND_INFO
#define BLE_ATT_SVR_FIND_INFO (1)
#endif

#ifndef BLE_ATT_SVR_FIND_TYPE
#define BLE_ATT_SVR_FIND_TYPE (1)
#endif

#ifndef BLE_ATT_SVR_INDICATE
#define BLE_ATT_SVR_INDICATE (1)
#endif

#ifndef BLE_ATT_SVR_MAX_PREP_ENTRIES
#define BLE_ATT_SVR_MAX_PREP_ENTRIES (64)
#endif

#ifndef BLE_ATT_SVR_NOTIFY
#define BLE_ATT_SVR_NOTIFY (1)
#endif

#ifndef BLE_ATT_SVR_QUEUED_WRITE
#define BLE_ATT_SVR_QUEUED_WRITE (1)
#endif

#ifndef BLE_ATT_SVR_QUEUED_WRITE_TMO
#define BLE_ATT_SVR_QUEUED_WRITE_TMO (30000)
#endif

#ifndef BLE_ATT_SVR_READ
#define BLE_ATT_SVR_READ (1)
#endif

#ifndef BLE_ATT_SVR_READ_BLOB
#define BLE_ATT_SVR_READ_BLOB (1)
#endif

#ifndef BLE_ATT_SVR_READ_GROUP_TYPE
#define BLE_ATT_SVR_READ_GROUP_TYPE (1)
#endif

#ifndef BLE_ATT_SVR_READ_MULT
#define BLE_ATT_SVR_READ_MULT (1)
#endif

#ifndef BLE_ATT_SVR_READ_TYPE
#define BLE_ATT_SVR_READ_TYPE (1)
#endif

#ifndef BLE_ATT_SVR_SIGNED_WRITE
#define BLE_ATT_SVR_SIGNED_WRITE (1)
#endif

#ifndef BLE_ATT_SVR_WRITE
#define BLE_ATT_SVR_WRITE (1)
#endif

#ifndef BLE_ATT_SVR_WRITE_NO_RSP
#define BLE_ATT_SVR_WRITE_NO_RSP (1)
#endif

#ifndef BLE_GAP_MAX_PENDING_CONN_PARAM_UPDATE
#define BLE_GAP_MAX_PENDING_CONN_PARAM_UPDATE (1)
#endif

#ifndef BLE_GATT_DISC_ALL_CHRS
#define BLE_GATT_DISC_ALL_CHRS (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_DISC_ALL_DSCS
#define BLE_GATT_DISC_ALL_DSCS (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_DISC_ALL_SVCS
#define BLE_GATT_DISC_ALL_SVCS (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_DISC_CHR_UUID
#define BLE_GATT_DISC_CHR_UUID (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_DISC_SVC_UUID
#define BLE_GATT_DISC_SVC_UUID (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_FIND_INC_SVCS
#define BLE_GATT_FIND_INC_SVCS (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_INDICATE
#define BLE_GATT_INDICATE (1)
#endif

#ifndef BLE_GATT_MAX_PROCS
#define BLE_GATT_MAX_PROCS (4)
#endif

#ifndef BLE_GATT_NOTIFY
#define BLE_GATT_NOTIFY (1)
#endif

#ifndef BLE_GATT_READ
#define BLE_GATT_READ (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_READ_LONG
#define BLE_GATT_READ_LONG (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_READ_MAX_ATTRS
#define BLE_GATT_READ_MAX_ATTRS (8)
#endif

#ifndef BLE_GATT_READ_MULT
#define BLE_GATT_READ_MULT (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_READ_UUID
#define BLE_GATT_READ_UUID (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_RESUME_RATE
#define BLE_GATT_RESUME_RATE (1000)
#endif

#ifndef BLE_GATT_SIGNED_WRITE
#define BLE_GATT_SIGNED_WRITE (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_WRITE
#define BLE_GATT_WRITE (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_WRITE_LONG
#define BLE_GATT_WRITE_LONG (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_WRITE_MAX_ATTRS
#define BLE_GATT_WRITE_MAX_ATTRS (4)
#endif

#ifndef BLE_GATT_WRITE_NO_RSP
#define BLE_GATT_WRITE_NO_RSP (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_GATT_WRITE_RELIABLE
#define BLE_GATT_WRITE_RELIABLE (BLE_ROLE_CENTRAL)
#endif

#ifndef BLE_HOST
#define BLE_HOST (1)
#endif

#ifndef BLE_HS_AUTO_START
#define BLE_HS_AUTO_START (1)
#endif

#ifndef BLE_HS_DEBUG
#define BLE_HS_DEBUG (0)
#endif

#ifndef BLE_HS_FLOW_CTRL
#define BLE_HS_FLOW_CTRL (0)
#endif

#ifndef BLE_HS_FLOW_CTRL_ITVL
#define BLE_HS_FLOW_CTRL_ITVL (1000)
#endif

#ifndef BLE_HS_FLOW_CTRL_THRESH
#define BLE_HS_FLOW_CTRL_THRESH (2)
#endif

#ifndef BLE_HS_FLOW_CTRL_TX_ON_DISCONNECT
#define BLE_HS_FLOW_CTRL_TX_ON_DISCONNECT (0)
#endif

#ifndef BLE_HS_PHONY_HCI_ACKS
#define BLE_HS_PHONY_HCI_ACKS (0)
#endif

#ifndef BLE_HS_REQUIRE_OS
#define BLE_HS_REQUIRE_OS (1)
#endif

#ifndef BLE_L2CAP_COC_MAX_NUM
#define BLE_L2CAP_COC_MAX_NUM (0)
#endif

#ifndef BLE_L2CAP_JOIN_RX_FRAGS
#define BLE_L2CAP_JOIN_RX_FRAGS (1)
#endif

#ifndef BLE_L2CAP_MAX_CHANS
#define BLE_L2CAP_MAX_CHANS (3*BLE_MAX_CONNECTIONS)
#endif

#ifndef BLE_L2CAP_RX_FRAG_TIMEOUT
#define BLE_L2CAP_RX_FRAG_TIMEOUT (30000)
#endif

#ifndef BLE_L2CAP_SIG_MAX_PROCS
#define BLE_L2CAP_SIG_MAX_PROCS (1)
#endif

#ifndef BLE_MESH
#define BLE_MESH (0)
#endif

#ifndef BLE_MONITOR_CONSOLE_BUFFER_SIZE
#define BLE_MONITOR_CONSOLE_BUFFER_SIZE (128)
#endif

#ifndef BLE_MONITOR_RTT
#define BLE_MONITOR_RTT (0)
#endif

#ifndef BLE_MONITOR_RTT_BUFFERED
#define BLE_MONITOR_RTT_BUFFERED (1)
#endif

#ifndef BLE_MONITOR_RTT_BUFFER_NAME
#define BLE_MONITOR_RTT_BUFFER_NAME ("monitor")
#endif

#ifndef BLE_MONITOR_RTT_BUFFER_SIZE
#define BLE_MONITOR_RTT_BUFFER_SIZE (256)
#endif

#ifndef BLE_MONITOR_UART
#define BLE_MONITOR_UART (0)
#endif

#ifndef BLE_MONITOR_UART_BAUDRATE
#define BLE_MONITOR_UART_BAUDRATE (1000000)
#endif

#ifndef BLE_MONITOR_UART_BUFFER_SIZE
#define BLE_MONITOR_UART_BUFFER_SIZE (64)
#endif

#ifndef BLE_MONITOR_UART_DEV
#define BLE_MONITOR_UART_DEV ("uart0")
#endif

#ifndef BLE_RPA_TIMEOUT
#define BLE_RPA_TIMEOUT (300)
#endif

#ifndef BLE_SM_BONDING
#define BLE_SM_BONDING (0)
#endif

#ifndef BLE_SM_IO_CAP
#define BLE_SM_IO_CAP (BLE_HS_IO_NO_INPUT_OUTPUT)
#endif

#ifndef BLE_SM_KEYPRESS
#define BLE_SM_KEYPRESS (0)
#endif

#ifndef BLE_SM_LEGACY
#define BLE_SM_LEGACY (1)
#endif

#ifndef BLE_SM_MAX_PROCS
#define BLE_SM_MAX_PROCS (1)
#endif

#ifndef BLE_SM_MITM
#define BLE_SM_MITM (0)
#endif

#ifndef BLE_SM_OOB_DATA_FLAG
#define BLE_SM_OOB_DATA_FLAG (0)
#endif

#ifndef BLE_SM_OUR_KEY_DIST
#define BLE_SM_OUR_KEY_DIST (0)
#endif

#ifndef BLE_SM_SC
#define BLE_SM_SC (0)
#endif

#ifndef BLE_SM_THEIR_KEY_DIST
#define BLE_SM_THEIR_KEY_DIST (0)
#endif

#ifndef BLE_STORE_MAX_BONDS
#define BLE_STORE_MAX_BONDS (3)
#endif

#ifndef BLE_STORE_MAX_CCCDS
#define BLE_STORE_MAX_CCCDS (8)
#endif

#ifndef BLE_HS_STOP_ON_SHUTDOWN_TIMEOUT
#define BLE_HS_STOP_ON_SHUTDOWN_TIMEOUT (2000)
#endif

/*** nimble/host/services/ans */
#ifndef BLE_SVC_ANS_NEW_ALERT_CAT
#define BLE_SVC_ANS_NEW_ALERT_CAT (0)
#endif

#ifndef BLE_SVC_ANS_UNR_ALERT_CAT
#define BLE_SVC_ANS_UNR_ALERT_CAT (0)
#endif

/*** nimble/host/services/bas */
#ifndef BLE_SVC_BAS_BATTERY_LEVEL_NOTIFY_ENABLE
#define BLE_SVC_BAS_BATTERY_LEVEL_NOTIFY_ENABLE (1)
#endif

#ifndef BLE_SVC_BAS_BATTERY_LEVEL_READ_PERM
#define BLE_SVC_BAS_BATTERY_LEVEL_READ_PERM (0)
#endif

/*** nimble/host/services/gap */
#ifndef BLE_SVC_GAP_APPEARANCE
#define BLE_SVC_GAP_APPEARANCE (0)
#endif

#ifndef BLE_SVC_GAP_APPEARANCE_WRITE_PERM
#define BLE_SVC_GAP_APPEARANCE_WRITE_PERM (-1)
#endif

#ifndef BLE_SVC_GAP_CENTRAL_ADDRESS_RESOLUTION
#define BLE_SVC_GAP_CENTRAL_ADDRESS_RESOLUTION (-1)
#endif

#ifndef BLE_SVC_GAP_DEVICE_NAME
#define BLE_SVC_GAP_DEVICE_NAME ("nimble")
#endif

#ifndef BLE_SVC_GAP_DEVICE_NAME_MAX_LENGTH
#define BLE_SVC_GAP_DEVICE_NAME_MAX_LENGTH (31)
#endif

#ifndef BLE_SVC_GAP_DEVICE_NAME_WRITE_PERM
#define BLE_SVC_GAP_DEVICE_NAME_WRITE_PERM (-1)
#endif

#ifndef BLE_SVC_GAP_PPCP_MAX_CONN_INTERVAL
#define BLE_SVC_GAP_PPCP_MAX_CONN_INTERVAL (0)
#endif

#ifndef BLE_SVC_GAP_PPCP_MIN_CONN_INTERVAL
#define BLE_SVC_GAP_PPCP_MIN_CONN_INTERVAL (0)
#endif

#ifndef BLE_SVC_GAP_PPCP_SLAVE_LATENCY
#define BLE_SVC_GAP_PPCP_SLAVE_LATENCY (0)
#endif

#ifndef BLE_SVC_GAP_PPCP_SUPERVISION_TMO
#define BLE_SVC_GAP_PPCP_SUPERVISION_TMO (0)
#endif

/*** nimble/transport */
#ifndef BLE_HCI_TRANSPORT_EMSPI
#define BLE_HCI_TRANSPORT_EMSPI (0)
#endif

/* Overridden by targets/porting-nimble (defined by nimble/transport) */
#ifndef BLE_HCI_TRANSPORT_NIMBLE_BUILTIN
#define BLE_HCI_TRANSPORT_NIMBLE_BUILTIN (0)
#endif

#ifndef BLE_HCI_TRANSPORT_RAM
#define BLE_HCI_TRANSPORT_RAM (0)
#endif

#ifndef BLE_HCI_TRANSPORT_SOCKET
#define BLE_HCI_TRANSPORT_SOCKET (0)
#endif

/* Overridden by targets/porting-nimble (defined by nimble/transport) */
#ifndef BLE_HCI_TRANSPORT_UART
#define BLE_HCI_TRANSPORT_UART (1)
#endif

/*** nimble/transport/uart */
#ifndef BLE_ACL_BUF_COUNT
#define BLE_ACL_BUF_COUNT (12)
#endif

#ifndef BLE_ACL_BUF_SIZE
#define BLE_ACL_BUF_SIZE (255)
#endif

#ifndef BLE_HCI_ACL_OUT_COUNT
#define BLE_HCI_ACL_OUT_COUNT (12)
#endif

#ifndef BLE_HCI_EVT_BUF_SIZE
#define BLE_HCI_EVT_BUF_SIZE (70)
#endif

#ifndef BLE_HCI_EVT_HI_BUF_COUNT
#define BLE_HCI_EVT_HI_BUF_COUNT (8)
#endif

#ifndef BLE_HCI_EVT_LO_BUF_COUNT
#define BLE_HCI_EVT_LO_BUF_COUNT (8)
#endif

/* Overridden by targets/porting-nimble (defined by nimble/transport/uart) */
#ifndef BLE_HCI_UART_BAUD
#define BLE_HCI_UART_BAUD (115200)
#endif

#ifndef BLE_HCI_UART_DATA_BITS
#define BLE_HCI_UART_DATA_BITS (8)
#endif

/* Overridden by targets/porting-nimble (defined by nimble/transport/uart) */
#ifndef BLE_HCI_UART_FLOW_CTRL
#define BLE_HCI_UART_FLOW_CTRL (0)
#endif

#ifndef BLE_HCI_UART_PARITY
#define BLE_HCI_UART_PARITY (HAL_UART_PARITY_NONE)
#endif

#ifndef BLE_HCI_UART_PORT
#define BLE_HCI_UART_PORT (0)
#endif

#ifndef BLE_HCI_UART_STOP_BITS
#define BLE_HCI_UART_STOP_BITS (1)
#endif

/*** sys/console/stub */
#ifndef CONSOLE_UART_BAUD
#define CONSOLE_UART_BAUD (115200)
#endif

#ifndef CONSOLE_UART_DEV
#define CONSOLE_UART_DEV ("uart0")
#endif

#ifndef CONSOLE_UART_FLOW_CONTROL
#define CONSOLE_UART_FLOW_CONTROL (UART_FLOW_CTL_NONE)
#endif

/*** sys/flash_map */
#ifndef FLASH_MAP_MAX_AREAS
#define FLASH_MAP_MAX_AREAS (10)
#endif

/*** sys/log/stub */
#ifndef LOG_CONSOLE
#define LOG_CONSOLE (1)
#endif

#ifndef LOG_FCB
#define LOG_FCB (0)
#endif

#ifndef LOG_LEVEL
#define LOG_LEVEL (255)
#endif

/*** sys/sysinit */
#ifndef SYSINIT_CONSTRAIN_INIT
#define SYSINIT_CONSTRAIN_INIT (1)
#endif

#ifndef SYSINIT_PANIC_FILE_LINE
#define SYSINIT_PANIC_FILE_LINE (0)
#endif

#ifndef SYSINIT_PANIC_MESSAGE
#define SYSINIT_PANIC_MESSAGE (0)
#endif

#endif
