void sysinit_app(void);

void os_pkg_init(void);
void flash_map_init(void);
void uart_bitbang_pkg_init(void);
void stats_module_init(void);
void console_pkg_init(void);
void config_pkg_init(void);
void fault_init(void);
void ble_hci_emspi_init(void);
void ble_hci_ram_init(void);
void log_init(void);
void modlog_init(void);
void mfg_init(void);
void sysview_init(void);
void log_reboot_pkg_init(void);
void ble_hs_init(void);
void config_pkg_init_stage2(void);
void ble_ll_init(void);
void ble_svc_gap_init(void);
void ble_svc_gatt_init(void);
void ble_svc_bas_init(void);
void ble_svc_tps_init(void);
void ble_svc_dis_init(void);
void ble_svc_ipss_init(void);
void ble_svc_ans_init(void);
void ble_svc_ias_init(void);
void ble_svc_lls_init(void);
void bleuart_init(void);
void shell_init(void);
void ble_store_config_init(void);
void ble_store_ram_init(void);
void bt_mesh_register_gatt(void);
void ble_hci_sock_init(void);
void id_init(void);
void ble_hci_uart_init(void);
void metrics_pkg_init(void);
void fault_cli_init(void);
void ble_mesh_shell_init(void);

void sysinit_app(void)
{
   os_pkg_init();
//   flash_map_init();
//   uart_bitbang_pkg_init();
//   stats_module_init();
//   console_pkg_init();
//   config_pkg_init();
   fault_init();
//   ble_hci_emspi_init();
   ble_hci_ram_init();
//   log_init();
//   modlog_init();
//   mfg_init();
//   sysview_init();
//   log_reboot_pkg_init();
   ble_hs_init();
//   config_pkg_init_stage2();
   ble_ll_init();
   ble_svc_gap_init();
   ble_svc_gatt_init();
   ble_svc_bas_init();
   ble_svc_tps_init();
   ble_svc_dis_init();
   ble_svc_ipss_init();
   ble_svc_ans_init();
   ble_svc_ias_init();
   ble_svc_lls_init();
   bleuart_init();
   shell_init();
   ble_store_config_init();
   ble_store_ram_init();
//   bt_mesh_register_gatt();
//   ble_hci_sock_init();
//   id_init();
//   ble_hci_uart_init();
//   metrics_pkg_init();
//   fault_cli_init();
//   ble_mesh_shell_init();
}
